/**
 * BillScan Hashing — BLAKE3 ONLY
 * 
 * Uses @noble/hashes BLAKE3 implementation (pure JS, audited, zero dependencies).
 * No fallback to SHA-256. BLAKE3 is faster, more secure, and purpose-built
 * for integrity verification.
 * 
 * Reference: https://github.com/BLAKE3-team/BLAKE3
 */

import { blake3 } from '@noble/hashes/blake3.js';
import { readFileSync } from 'node:fs';

const ALGORITHM = 'blake3';

/**
 * Hash arbitrary data with BLAKE3.
 * Returns a prefixed string: "blake3:<hex>"
 */
export async function hash(data: Buffer | string): Promise<string> {
  const buf = typeof data === 'string' ? Buffer.from(data, 'utf-8') : data;
  const hashBytes = blake3(new Uint8Array(buf));
  return `${ALGORITHM}:${Buffer.from(hashBytes).toString('hex')}`;
}

/**
 * Hash a file with BLAKE3.
 * Reads the entire file into memory (fine for medical bill images/PDFs under 10MB).
 * Returns a prefixed string: "blake3:<hex>"
 */
export async function hashFile(filePath: string): Promise<string> {
  const data = readFileSync(filePath);
  const hashBytes = blake3(new Uint8Array(data));
  return `${ALGORITHM}:${Buffer.from(hashBytes).toString('hex')}`;
}

/**
 * Get the algorithm name from a hash string.
 * Always returns 'blake3' for hashes generated by this module.
 */
export function getAlgorithm(hashString: string): string {
  return hashString.split(':')[0];
}

/**
 * Hash data synchronously (for cases where async isn't needed).
 */
export function hashSync(data: Buffer | string): string {
  const buf = typeof data === 'string' ? Buffer.from(data, 'utf-8') : data;
  const hashBytes = blake3(new Uint8Array(buf));
  return `${ALGORITHM}:${Buffer.from(hashBytes).toString('hex')}`;
}
